export const drafts = [
  {
    id: 0,
    content:
      "Iaculis, habitant facilisis nullam ultricies dui eget suspendisse ipsum urna hymenaeos sociis pellentesque vitae. Massa leo iaculis facilisi eleifend. Elit auctor nostra, mus eu. Et magnis magna augue tristique urna tortor sagittis litora imperdiet et feugiat tempus leo placerat vel dui ante egestas commodo luctus feugiat, placerat taciti curae; turpis Tincidunt orci. Senectus justo hymenaeos lacus hendrerit est penatibus hymenaeos at dictumst suspendisse sociis commodo varius pretium pretium venenatis et curae;. Lobortis interdum, sociosqu praesent cras purus mollis auctor ornare inceptos elit nunc, litora ante. Rutrum nonummy. Erat est ad. Dis. Fusce phasellus lacinia donec, vivamus dis urna nam lectus. Fames porta massa dolor fusce ultricies, proin, eget augue mollis tortor, vivamus senectus nec natoque proin risus etiam turpis curae; mi quis senectus proin condimentum lectus primis curabitur curabitur sed phasellus porttitor varius. Pharetra, pede penatibus sed senectus cursus tempor commodo laoreet per vulputate blandit nisl. Ultrices. Nostra aptent justo faucibus inceptos parturient augue quam pede pretium ac ac quam vel. Bibendum scelerisque magnis quam a dui sagittis ut eleifend mattis egestas nullam. Faucibus ut arcu netus aliquam mollis venenatis sit dictumst, fames imperdiet sociis tristique dis. Sodales vel neque phasellus ridiculus. Odio taciti mattis nisi ornare conubia ipsum aliquet.",
  },
  {
    id: 1,
    content:
      "Suspendisse ipsum urna hymenaeos sociis pellentesque vitae. Massa leo iaculis facilisi eleifend. Elit auctor nostra, mus eu. Et magnis magna augue tristique urna tortor sagittis litora imperdiet et feugiat tempus leo placerat vel dui ante egestas commodo luctus feugiat, placerat taciti curae; turpis Tincidunt orci. Senectus justo hymenaeos lacus hendrerit est penatibus hymenaeos at dictumst suspendisse sociis commodo varius pretium pretium venenatis et curae;. Lobortis interdum, sociosqu praesent cras purus mollis auctor ornare inceptos elit nunc, litora ante. Rutrum nonummy. Erat est ad. Dis. Fusce phasellus lacinia donec, vivamus dis urna nam lectus. Fames porta massa dolor fusce ultricies, proin, eget augue mollis tortor, vivamus senectus nec natoque proin risus etiam turpis curae; mi quis senectus proin condimentum lectus primis curabitur curabitur sed phasellus porttitor varius. Pharetra, pede penatibus sed senectus cursus tempor commodo laoreet per vulputate blandit nisl. Ultrices. Nostra aptent justo faucibus inceptos parturient augue quam pede pretium ac ac quam vel. Bibendum scelerisque magnis quam a dui sagittis ut eleifend mattis egestas nullam. Faucibus ut arcu netus aliquam mollis venenatis sit dictumst, fames imperdiet sociis tristique dis. Sodales vel neque phasellus ridiculus. Odio taciti mattis nisi ornare conubia ipsum aliquet.Iaculis, habitant facilisis nullam ultricies dui eget",
  },
  {
    id: 2,
    content:
      "Ultricies dui eget suspendisse ipsum urna hymenaeos sociis pellentesque vitae. Massa leo iaculis facilisi eleifend. Elit auctor nostra, mus eu. Et magnis magna augue tristique urna tortor sagittis litora imperdiet et feugiat tempus leo placerat vel dui ante egestas commodo luctus feugiat, placerat taciti curae; turpis Tincidunt orci. Senectus justo hymenaeos lacus hendrerit est penatibus hymenaeos at dictumst suspendisse sociis commodo varius pretium pretium venenatis et curae;. Lobortis interdum, sociosqu praesent cras purus mollis auctor ornare inceptos elit nunc, litora ante. Rutrum nonummy. Erat est ad. Dis. Fusce phasellus lacinia donec, vivamus dis urna nam lectus. Fames porta massa dolor fusce ultricies, proin, eget augue mollis tortor, vivamus senectus nec natoque proin risus etiam turpis curae; mi quis senectus proin condimentum lectus primis curabitur curabitur sed phasellus porttitor varius. Pharetra, pede penatibus sed senectus cursus tempor commodo laoreet per vulputate blandit nisl. Ultrices. Nostra aptent justo faucibus inceptos parturient augue quam pede pretium ac ac quam vel. Bibendum scelerisque magnis quam a dui sagittis ut eleifend mattis egestas nullam. Faucibus ut arcu netus aliquam mollis venenatis sit dictumst, fames imperdiet sociis tristique dis. Sodales vel neque phasellus ridiculus. Odio taciti mattis nisi ornare conubia ipsum aliquet. Iaculis, habitant facilisis nullam",
  },
  {
    id: 3,
    content:
      "Hymenaeos sociis pellentesque vitae. Massa leo iaculis facilisi eleifend. Elit auctor nostra, mus eu. Et magnis magna augue tristique urna tortor sagittis litora imperdiet et feugiat tempus leo placerat vel dui ante egestas commodo luctus feugiat, placerat taciti curae; turpis Tincidunt orci. Senectus justo hymenaeos lacus hendrerit est penatibus hymenaeos at dictumst suspendisse sociis commodo varius pretium pretium venenatis et curae;. Lobortis interdum, sociosqu praesent cras purus mollis auctor ornare inceptos elit nunc, litora ante. Rutrum nonummy. Erat est ad. Dis. Fusce phasellus lacinia donec, vivamus dis urna nam lectus. Fames porta massa dolor fusce ultricies, proin, eget augue mollis tortor, vivamus senectus nec natoque proin risus etiam turpis curae; mi quis senectus proin condimentum lectus primis curabitur curabitur sed phasellus porttitor varius. Pharetra, pede penatibus sed senectus cursus tempor commodo laoreet per vulputate blandit nisl. Ultrices. Nostra aptent justo faucibus inceptos parturient augue quam pede pretium ac ac quam vel. Bibendum scelerisque magnis quam a dui sagittis ut eleifend mattis egestas nullam. Faucibus ut arcu netus aliquam mollis venenatis sit dictumst, fames imperdiet sociis tristique dis. Sodales vel neque phasellus ridiculus. Odio taciti mattis nisi ornare conubia ipsum aliquet. Iaculis, habitant facilisis nullam ultricies dui eget suspendisse ipsum lorem.",
  },
];
